# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practical_TensorIOT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FirebaseAuth', '~> 10.16.0'
  pod 'FirebaseDatabase', '~> 10.16.0'
  pod 'FirebaseStorage', '~> 10.16.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.12'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'SDWebImage', '~> 5.18.2'
  pod 'SwiftKeychainWrapper', '~> 4.0.1'

end
